# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'japrb.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 361, 20))
        self.label.setObjectName("label")
        self.playBtn = QtWidgets.QPushButton(Dialog)
        self.playBtn.setGeometry(QtCore.QRect(60, 160, 99, 27))
        icon = QtGui.QIcon.fromTheme("SP_MediaPlay")
        self.playBtn.setIcon(icon)
        self.playBtn.setObjectName("playBtn")
        self.enterUrl = QtWidgets.QTextEdit(Dialog)
        self.enterUrl.setGeometry(QtCore.QRect(140, 70, 104, 78))
        self.enterUrl.setObjectName("enterUrl")
        self.setBtn = QtWidgets.QPushButton(Dialog)
        self.setBtn.setGeometry(QtCore.QRect(200, 160, 99, 27))
        self.setBtn.setObjectName("setBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Just press play and Metal will ring in your ears"))
        self.playBtn.setText(_translate("Dialog", "play"))
        self.setBtn.setText(_translate("Dialog", "set station"))
